spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://admin:admin@pspatel.dkytwcf.mongodb.net/?retryWrites=true&w=majority
#      database: user_db
#      host: localhost
#      port: 27017
  # Database Link: mongodb+srv://admin:admin@pspatel.dkytwcf.mongodb.net/?retryWrites=true&w=majority

  mail:
    host: smtp.gmail.com
    port: 587
    username: pspatel602@gmail.com
    password: ipaoavopoxboihwt

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

